### ISSUE TITLE
Deprecated selector in `mesa-syntax/index.less`

### ISSUE THREAD

**Issue by rcrooks** [SydLambert/atom-mesa-syntax#1]
Hi, very nice syntax theme. You should update the deprecated selectors, though -- see below.

In `mesa-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .bracket-matcher .region` => `atom-text-editor.editor .bracket-matcher .region`

* `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,
:host(.is-focused) .line-number.cursor-line-no-selection,
:host(.is-focused) .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by SydLambert** [comment]
Thanks, I have now updated the old selectors as of version v0.2.1.

**Comment by rcrooks** [comment]
Thanks!
